shared/u-boot: Cleanup unused function
This commit adds 'HAS_UBOOT' conditional to 'bsp_uboot_getenv' to match
the bsp.h file.

This fixes the following errors:
     error: home/tester/bsps/powerpc/shared/u-boot/uboot_getenv.c:73:13:
            error: no previous prototype for 'bsp_uboot_getenv'
            [-Werror=missing-prototypes]

Updates #5481