bsps/arm/xilinx-zynq/start/bspsmp.c: fix unused parameter warning
Fixes following unused parameter warning (treated as error) in build
without assertions.

[  25/1550] Compiling bsps/arm/xilinx-zynq/start/bspsmp.c
../../../bsps/arm/xilinx-zynq/start/bspsmp.c: In function
'_CPU_SMP_Start_processor':
../../../bsps/arm/xilinx-zynq/start/bspsmp.c:42:40: error:
unused parameter 'cpu_index' [-Werror=unused-parameter]
   42 | bool _CPU_SMP_Start_processor(uint32_t cpu_index)
      |                               ~~~~~~~~~^~~~~~~~~
cc1: all warnings being treated as errors

Happens if arm/xilinx_zynq_zedboard board is configured and RTEMS_SMP
is enabled.

Signed-off-by: Michal Lenc <michallenc@seznam.cz>