bsps/leon3: Fix LEON3 timer register store
Fix the this compiler error introduced by commit
d9de3dac5d609a9fe0f551ce4859fa1583a39c8e:

bsps/sparc/leon3/start/amba.c: In function 'amba_initialize':
bsps/sparc/leon3/start/amba.c:221:32: error: passing argument 1 of
'grlib_store_32' makes pointer from integer without a cast
[-Wint-conversion]
  221 |       grlib_store_32(timer_regs->sreload, leon3_timer_prescaler);

Tested with the following config.ini:

[sparc/gr740]
LEON3_GPTIMER_BASE =

Update #5541.

Signed-off-by: Sebastian Huber <sebastian.huber@embedded-brains.de>
(cherry picked from commit c66a0efb45fa080abb081f34af3379e6ae35970d)