score: Include missing header file
This fixes:

heap.c:268:3: warning: implicit declaration of function 'memset'

(cherry picked from commit 9e0bcd4fc77099a064b21e789ea5724dc5de55c3)