libi2c: Fix unused parameter error
Fix the following errors:

```
cpukit/libi2c/libi2c.c: In function 'rtems_i2c_init':
cpukit/libi2c/libi2c.c:162:29:
error: unused parameter 'minor' [-Werror=unused-parameter]
  162 |   rtems_device_minor_number minor,
      |   ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~
cpukit/libi2c/libi2c.c:163:29:
error: unused parameter 'arg' [-Werror=unused-parameter]
  163 |   void                     *arg
      |   ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~
```

Updates #5678.

Signed-off-by: Sebastian Huber <sebastian.huber@embedded-brains.de>