bsps/altera-cyclone-v: Fix warning
bsps/arm/altera-cyclone-v/contrib/hwlib/src/hwmgr/alt_qspi.c:
In function 'alt_qspi_read':
bsps/arm/altera-cyclone-v/contrib/hwlib/src/hwmgr/alt_qspi.c:747:12:
error: variable 'data' set but not used
[-Werror=unused-but-set-variable=]
  747 |     char * data = (char *)dst;
      |            ^~~~

Signed-off-by: Sebastian Huber <sebastian.huber@embedded-brains.de>